// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3URTXMFgvSXtVZqrO_aa3tdw4BcqDE_o',
    appId: '1:93065379858:web:841ad1c9c619569ea218cb',
    messagingSenderId: '93065379858',
    projectId: 'sa7tey-ac1ba',
    authDomain: 'sa7tey-ac1ba.firebaseapp.com',
    storageBucket: 'sa7tey-ac1ba.firebasestorage.app',
    measurementId: 'G-MJCRXF3LTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIFbxh0NcXj1OZBAoi4aNsdhfogWDLhXo',
    appId: '1:93065379858:android:adbc251ed5303a37a218cb',
    messagingSenderId: '93065379858',
    projectId: 'sa7tey-ac1ba',
    storageBucket: 'sa7tey-ac1ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRVnogXM7sMNIzrc-Jx2kAsmPzczlpjI',
    appId: '1:93065379858:ios:eb1df23c0a447ac1a218cb',
    messagingSenderId: '93065379858',
    projectId: 'sa7tey-ac1ba',
    storageBucket: 'sa7tey-ac1ba.firebasestorage.app',
    iosBundleId: 'com.example.sa7ty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRVnogXM7sMNIzrc-Jx2kAsmPzczlpjI',
    appId: '1:93065379858:ios:eb1df23c0a447ac1a218cb',
    messagingSenderId: '93065379858',
    projectId: 'sa7tey-ac1ba',
    storageBucket: 'sa7tey-ac1ba.firebasestorage.app',
    iosBundleId: 'com.example.sa7ty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3URTXMFgvSXtVZqrO_aa3tdw4BcqDE_o',
    appId: '1:93065379858:web:0d5d3a4002dc96f7a218cb',
    messagingSenderId: '93065379858',
    projectId: 'sa7tey-ac1ba',
    authDomain: 'sa7tey-ac1ba.firebaseapp.com',
    storageBucket: 'sa7tey-ac1ba.firebasestorage.app',
    measurementId: 'G-X3VK87884N',
  );
}
